{% set name = "ai2thor" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30f8721db3582d54cfe68c218322c038b9c2611c2973f495e32d12f760887d46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - aws-requests-auth
    - flask
    - msgpack-python
    - numpy
    - opencv
    - pillow
    - progressbar2
    - python >=3.6
    - python-xlib
    - botocore
    - requests
    - werkzeug >=0.15.0

test:
  imports:
    - ai2thor
    - ai2thor.util

about:
  home: https://github.com/allenai/ai2thor
  summary: AI2 Thor is a lightweight AI framework that interacts with the Unity3d Game Engine.
  license: Apache-2.0
  # check later once the license file is included in the source distribution 
  license_file: LICENSE

extra:
  recipe-maintainers:
    - systemshift
    - ekolve
