{% set name = "ai2thor" %}
{% set version = "5.0.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 652298820c3c677579fc179232f1ccac0d5b9bc98b1f59baf7c0698d0e478758

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aws-requests-auth
    - flask
    - msgpack-python
    - numpy
    - opencv
    - pillow
    - progressbar2
    - python >={{ python_min }}
    - python-xlib
    - pyyaml
    - botocore
    - requests
    - werkzeug >=0.15.0

test:
  requires:
    - python {{ python_min }}
    - pytest-runner
  imports:
    - ai2thor
    - ai2thor.util

about:
  home: https://github.com/allenai/ai2thor
  summary: AI2 Thor is a lightweight AI framework that interacts with the Unity3d Game Engine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giotherobot
    - systemshift
    - ekolve
